* License

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 3, or (at your option)
 any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; see the file COPYING.
 If not, see <http://www.gnu.org/licenses/>.

* Commentary

 Bitcoin donations gratefully accepted: 12k9zUo9Dgqk8Rary2cuzyvAQWD5EAuZ4q

 This library provides various miscellaneous `dired' related commands & functions
 that I use occasionally. 


* Commands

 Below is a complete command list:

 - `dired-get-size'
    Get total size of marked files using linux du command. This only works on local directories.
 - `dired-up-dir'
    In dired go up a directory and replace current buffer, instead of creating a new one.
 - `dired-do-shell-command-regexp'
    Create and run shell commands from selected filenames which match REGEXP.
 - `dired-find-file-other-window'
    Wrapper around dired-find-file-other-window.
 - `image-dired-show-all-tags'
    Show all tags that have been used to tag files.
 - `image-dired-display-thumbnail-original-image-fullsize'
    Display current thumbnail's original fullsize image in display buffer.
 - `image-dired-rename-original'
    Rename original file corresponding to current thumbnail.
 - `image-dired-copy-original'
    Copy original file corresponding to current thumbnail.

 The following existing commands are advised:

  `image-dired-display-thumbnail-original-image'
    Display current thumbnail's original image in display buffer.
  `image-dired-thumbnail-display-external'
    Display current thumbnail externally using `run-associated-program' (if installed).

* Installation

 Put dired-jb-misc-extras.el in a directory in your load-path, e.g. ~/.emacs.d/
 You can add a directory to your load-path with the following line in ~/.emacs
 (add-to-list 'load-path (expand-file-name "~/elisp"))
 where ~/elisp is the directory you want to add 
 (you don't need to do this for ~/.emacs.d - it's added by default).

 Add the following to your ~/.emacs startup file.

 (require 'dired-jb-misc-extras)
